### ISSUE TITLE
Ability to specify country

### ISSUE THREAD

**Issue by joe-budge** [realmayus/anki_forvo_dl#11]
Hi,
I think the ability to specify the country you want, as well as the language, would be very useful. For example, if you only wanted European Spanish audio rather than having a mix of Latin and European Spanish. Same idea with European and Brazilian Portuguese, Canadian and European French, etc.

**Comment by realmayus** [comment]
Thanks for the suggestion! I could allow the users to select a country preference, and if there's no recording from that country the other pronunciations would be used as the fallback. I'll put it on my todo list!

**Comment by intersulsul** [comment]
Or instead of adding ability to specify country, just make a country display next to each audio. It's simpler and faster. This feature is REALLY missing because with some languages (especially when you're only a beginner and can't differentiate much between accents) it's really important to choose the right dialect.

**Comment by realmayus** [comment]
Region information was added by https://github.com/realmayus/anki_forvo_dl/commit/32d8007eed2b7111369755a3ba787f6d71bf8779
